# Generated by Django 3.2.21 on 2024-02-06 13:53

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mutationlog_autogenerated_code'),
        ('payment_cycle', '0002_add_pc_rights_to_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCycleMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_cycle', to='core.mutationlog')),
                ('payment_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='payment_cycle.paymentcycle')),
            ],
            options={
                'db_table': 'payment_cycle_PaymentCycleMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
